In [ ]:
# pip install joblib


In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
plt.style.use('fivethirtyeight')

In [38]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3)*1e-4
        self.eta=eta #learning rate
        self.epochs = epochs # number of iteration
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs,weights)
    def activation_function(self,z):
        return np.where(z>0,1,0)
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias=np.c_[self.X,-np.ones(((len(self.X)),1))]
        print(X_with_bias)
#         self.z=_z_cal()
        for epoch in range(self.epochs):
            print("__"*10)
            print(f'for epoch: {epoch+1}')
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            
            print(f'predicted value after forward pass: \n{y_hat}')
            
            self.error = self.y-y_hat
            print(f'error : \n{self.error}')
            
            self.weights = self.weights + self.eta*np.dot(X_with_bias.T,self.error)
            print(f'Updated weights after epoch : {epoch +1}/{self.epochs} \n{self.weights}')
    def predict(self,X):
        X_with_bais = np.c_[X,-np.ones(((len(X)),1))]
        z=self._z_outcome(X_with_bais,self.weights)
        return self.activation_function(z)
        

In [39]:
obj= Perceptron(eta=.2,epochs=10)

In [40]:
OR ={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}
df_or = pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [45]:
AND ={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}
df_and = pd.DataFrame(AND)
df_and

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [46]:
def prepare_data(df, target_col='y'):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return X, y

In [48]:
X,y = prepare_data(df_and)
ETA= 0.1
EPOCHS = 10
model_and = Perceptron(eta=ETA, epochs=EPOCHS)
model_and.fit(X,y)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
____________________
for epoch: 1
predicted value after forward pass: 
[1 1 0 0]
error : 
0   -1
1   -1
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch : 1/10 
[9.98616217e-02 4.88378852e-05 9.99127134e-02]
____________________
for epoch: 2
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch : 2/10 
[ 1.99861622e-01  1.00048838e-01 -8.72865745e-05]
____________________
for epoch: 3
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epoch : 3/10 
[9.98616217e-02 4.88378852e-05 2.99912713e-01]
____________________
for epoch: 4
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch : 4/10 
[0.19986162 0.10004884 0.19991271]
____________________
for epoch: 5
predicted value after 

In [49]:
xor ={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,0]
}
df_xor = pd.DataFrame(xor)
df_xor

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [50]:
X,y = prepare_data(df_xor)
ETA= 0.1
EPOCHS = 10
model_xor = Perceptron(eta=ETA, epochs=EPOCHS)
model_xor.fit(X,y)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
____________________
for epoch: 1
predicted value after forward pass: 
[0 1 0 0]
error : 
0    0
1    0
2    1
3    0
Name: y, dtype: int64
Updated weights after epoch : 1/10 
[ 0.0999219   0.000151   -0.09989023]
____________________
for epoch: 2
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights after epoch : 2/10 
[-7.81023823e-05 -9.98489975e-02  1.00109772e-01]
____________________
for epoch: 3
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights after epoch : 3/10 
[ 0.0999219   0.000151   -0.09989023]
____________________
for epoch: 4
predicted value after forward pass: 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights after epoch : 4/10 
[-7.81023823e-05 -9.98489975e-02  1.00109772e-01]
____________________
for epoch: 5
predicted value after for