In [2]:
# pip install joblib


  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
plt.style.use('fivethirtyeight')

In [20]:
class Perceptron:
    def __init__(self,eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3)*1e-4
        self.eta=eta #learning rate
        self.epochs = epochs # number of iteration
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias=np.c_[self.X,-np.ones(((len(self.X)),1))]
        print(X_with_bias)
#         self.z=_z_cal()

In [21]:
obj= Perceptron(.2,10)

In [22]:
X=[[1,1],[0,1],[1,0]]
y=[[1],[1],[1]]
obj.fit(X,y)

[[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]]
